6
glebssha/1_contest pull request #7
Opened 2020-09-23 10:49 UTC by GlebShabuldaev

https://contest.yandex.ru/contest/19592/run-report/34680777/

2020-09-26 21:57 UTC, zhukovp0101 requested changes

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  T GetMax() const;
const T&

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  }
buf_ = std::move(buf)

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +Heap<T>::Heap(std::vector<T> buf, int size) {
да и size здесь лишний
есть buf_.size()

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +    return buf_[0];
если пусто, то должно что-нибудь произойти

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +    vector.push_back(node);
push_back(Node{i, value}) или emplace_back(i, value)
n тут не нужно. Тем более по ссылке его передавать не нужно

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  Heap<Point> heap(v, window_size);                 //В куче элементов будет больше, чем размер окна, но мы работаем
все равно нет смысла передавать в кучу два параметра. Это не проблема кучи, что элементов в массиве слишком много

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  void Pop(int index);
с точки зрения пользователя кучи Pop не должен уметь принимать параметр

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  }
красивое решение, правда читерское

2020-09-26 21:57 UTC, zhukovp0101 commented on main.cpp
> +  Point(int _index, int _value) : index(_index), value(_value) {}
можно и без _

2020-10-03 09:36 UTC, glebssha commented on main.cpp
> +    vector.push_back(node);
Не совсем понимаю, почему n не нужно. Мне ведь надо узнать, сколько элеметов запихивать в вектор. Как иначе?

2020-10-04 21:03 UTC, zhukovp0101 commented on main.cpp
> +  for (int i = 0; i < buf.size(); ++i) {
тут надо просто сделать buf_ = std::move(buf)

2020-10-04 21:03 UTC, zhukovp0101 commented on main.cpp
> +  for (int i = buf.size() - 1; i >= 0; --i) {
а тут, соответственно, buf_.size() использовать

2020-10-04 21:03 UTC, zhukovp0101 commented on main.cpp
> +const T& Heap<T>::GetMax() {
const в между ) { все равно нужен, это разные const'ы

2020-10-04 21:03 UTC, zhukovp0101 commented on main.cpp
> +    vector.push_back(node);
да, ошибся

2020-10-04 21:05 UTC, zhukovp0101 commented on main.cpp
> +    vector.push_back(node);
но push_back(Node{i, value}) сделай

2020-10-04 21:13 UTC, zhukovp0101 requested changes

2020-10-04 21:13 UTC, zhukovp0101 commented on main.cpp
> +  buf_.emplace_back(b);
move

2020-10-04 21:25 UTC, zhukovp0101 commented on main.cpp
> +  Heap<Point> heap(std::vector<Point>(v.begin(), v.begin()+window_size));                 //В куче элементов будет больше, чем размер окна, но мы работаем
Тут есть любопытная неоптимальность в виде двойного копирования данных из вектора. Сначала в это окно размера window_size, а потом еще раз окно копируется внутрь конструктора кучи. В c++20 для этой цели сделали span, который просто ссылается на данные, но не хранит их

2020-10-10 22:12 UTC, zhukovp0101 commented
Ок

2020-10-10 22:13 UTC, merged